from enum import Enum

class Vars(Enum):
    DEBUG_MODE = "DEBUG_MODE"
    API_HOST = "PYTHON_HOST"
    API_PORT =  "PYTHON_PORT"
    API_BASE_PATH = "API_BASE_PATH"
    LOG_LEVEL = "LOG_LEVEL" 
    ENV = "ENV"
    DIRECTORIO_LOGS = "DIRECTORIO_LOGS"
    DIRECTORIO_FILES = "DIRECTORIO_FILES"
    EMAIL_USER = "EMAIL_USER"
    EMAIL_ENVIADOR = "EMAIL_ENVIADOR"
    EMAIL_PASS = "EMAIL_PASS"
    VARIABLE_CONFIGURADA = "VARIABLE_CONFIGURADA"